apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ydg1jbbsz-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ydg1jbbsz-dotnet-basic